name: Benchmark

on: workflow_dispatch

jobs:
  linux:
    strategy:
      matrix:
        target: [ x64, ARM64 ]
        cxx_standard: [ 23 ]
        compiler:
          - { pkg: clang, exe: clang++, version: 22 }
        include:
          - target: x64
            os: ubuntu-26.04
          - target: ARM64
            os: ubuntu-26.04-arm
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6

      - name: CPM Cache
        uses: actions/cache@v5
        with:
          path: ${{github.workspace}}/.cpmcache
          key: cpm-${{runner.os}}-${{hashFiles('test/CMakeLists.txt')}}
          restore-keys: |
            cpm-${{runner.os}}-

      - name: Check Hardware
        run: lscpu | grep "Model name"

      - name: Configure
        env:
          CXX: ${{matrix.compiler.exe}}-${{matrix.compiler.version}}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_STANDARD=${{matrix.cxx_standard}} -DCMAKE_BUILD_TYPE=Release -DLIBHAT_TESTING_SDE=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build -j 4 --target libhat_benchmark_compare libhat_benchmark_chromium

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose -C Release -R "(libhat_benchmark_compare|libhat_benchmark_chromium)"
